name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    name: OTP ${{matrix.pair.otp}} / Elixir ${{matrix.pair.elixir}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              otp: 22.3
              elixir: 1.10.1
          - pair:
              otp: 23.2.5
              elixir: 1.11.3
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - name: Install → Compile dependencies
        run: |
          MIX_ENV=test mix do deps.get, deps.compile
      - name: Run tests
        run: |
          MIX_ENV=test mix test
          MIX_ENV=test mix coveralls.json
